### ISSUE TITLE
arealist未初始化导致SQL查询语句错误

### ISSUE THREAD

**Issue by differentrain** [amarillonmc/phpdts#211]
> 数据库错误。请联系管理员。
>
> 类错误信息：MySQL Query Error
> SQL语句：SELECT * FROM acbra2_players WHERE pls IN () AND hp>0
>
> 数据库错误提示：1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND hp>0' at line 1

---

问题描述和复现:

- 克隆主分支。
- 注释掉 `install.php` 文件中的 `require __DIR__ . '/vendor/autoload.php';`  语句。
- 创建 `acdts3` 数据库
- 导入 `gamedata\sql\all.sql` 。 
- 部署游戏。

此后，一旦开始游戏，则访问任何页面都会报此错误。

---

环境:

XAMPP+php 5.6.2

---
system.func.php:
```
$str_arealist = implode(',',array_slice($arealist,0,$areanum+1));
$query = $db->query("SELECT * FROM {$tablepre}players WHERE pls IN ($str_arealist) AND hp>0");
```
sql表:

```
{
	"table": "acbra2_game",
	"rows":
	[
		{
			"gamenum": 1,
			"gamestate": 10,
			"groomid": 0,
			"groomnums": 0,
			"groomownid": "",
			"starttime": 1727156863,
			"winmode": 0,
			"winner": "",
			"arealist": "",
			"areanum": 0,
			"areatime": 0,
			"areawarn": 0,
			"validnum": 0,
			"alivenum": 0,
			"deathnum": 0,
			"afktime": 1727156863,
			"optime": 1727156863,
			"weather": 0,
			"hack": 0,
			"hdamage": 0,
			"hplayer": "",
			"combonum": 160,
			"gamevars": "[]",
			"noisevars": "{\"noisetime\":0,\"noisepls\":0,\"noiseid\":0,\"noiseid2\":0,\"noisemode\":\"\"}"
		}
	]
}
```

**Comment by amarillonmc** [comment]
对于安装后第一局相关的各个地方的初始化应该是在运行``install.php``结束后做的，运行``install.php``后目前的逻辑会进入一个第1局游戏尚未开始的状态，需要手动去管理界面开始第1局，届时应该会初始化``arealist``。
虽说目前的主分支已经开始部署破世更新，但目前这里的代码中应该尚无涉及到``arealist``初始化相关的改动。

此外，目前的codebase的native PHP 版本已经上升到了7.4。自nachster以后的版本没有在5.6版本上测试过（虽然有生产环境跑的是5.6且没有明显问题）。

**Comment by differentrain** [comment]
> 对于安装后第一局相关的各个地方的初始化应该是在运行`install.php`结束后做的，运行`install.php`后目前的逻辑会进入一个第1局游戏尚未开始的状态，需要手动去管理界面开始第1局，届时应该会初始化`arealist`。 虽说目前的主分支已经开始部署破世更新，但目前这里的代码中应该尚无涉及到`arealist`初始化相关的改动。
> 
> 此外，目前的codebase的native PHP 版本已经上升到了7.4。自nachster以后的版本没有在5.6版本上测试过（虽然有生产环境跑的是5.6且没有明显问题）。

多谢回复，原因已找到，问题得到解决。
游戏的安装脚本缺失字段，导致游戏安装后，无法正确开始游戏。
当我尝试导入 `gamedata\sql\all.sql` 脚本时，没有检查SQL脚本的内容，导致它Drop掉了安装脚本添加的表和字段。
只要导入正确的脚本内容就可以解决，正常开始游戏了。
我不会PHP，所以在随后的PR中，会只更新一个整理后的SQL脚本。
